import { IAboutCard } from "../../interfaces/iabout-card";
import { IFAQCard } from "../../interfaces/ifaq-card";

export const kundliAboutCard: IAboutCard = {
    title: "What is a Kundli? A Closer Look at Your Cosmic Blueprint",
    column1: `
<div>
<h2> So, What Exactly is a Kundli? </h2>
</div>
<div>
Think of a Janam Kundli as the script of your life written by the positions of celestial bodies at the time of your birth, influenced by your place of birth in terms of its latitudes and longitudes, dasha analysis, and nakshatra analysis. Your vedic kundli is a birth chart, drawn from the time, date, and place you were born. Your AstroOrbits’ free kundli maps out where the planets were sitting in the sky and which houses they occupied. Every house, every placement carries meaning. Get your accurate and personalized kundli online for free at AstroOrbits. Use our kundli calculator today!
</div>
<div>
<strong>Expert Insight:</strong> "In our practice and experience, we have observed that a personalized janam patrika is like a DNA, no two are identical. Even twins born minutes apart can have different Lagnas (ascendants), and different kundli dosha remedy,  completely altering their life paths and personality traits."
</div>
<div>
<h2> Why Does It Matter?</h2>
</div>
<div>
Most people don’t turn to astrology because they’re looking for something to believe in. They turn to it because they’re trying to make sense of something. Maybe a phase that feels heavier than usual. Or a decision that’s looming.
</div>
<div>
Your Janam Patrika isn’t here to tell you what to do. But it can shed light on the emotional rhythms you live with. It can hint at the kinds of careers you’ll thrive in. It can help explain why some relationships feel effortless, while others demand more work.
</div>
<div>
It won’t give you hard answers. But sometimes, clarity isn’t about answers. It’s about better questions.
</div>
<div>
<strong>Classical Wisdom:</strong> As stated in Brihat Parashara Hora Shastra, Chapter 7, Shloka 12: "The position of planets at birth determines the native's karmic path and life experiences." This ancient wisdom guides our modern computational analysis, ensuring authenticity in every interpretation
</div>
<div>
<h2> Free Kundli Calculator At AstroOrbits</h2
</div>
<div>
Get Your Free Kundli Online 
</div>
<div>
AstroOrbits provides a free online Kundli Calculator, which generates an accurate and personalised Janam Patrika reports and analysis.  
</div>
<div>
To draw up an accurate Janam Patrika, you’ll need three things:
<ul>
<li>Your Full Name</li>
<li>Your Date of Birth </li>
<li>Your Time of Birth (don’t worry if you don’t know your exact time)</li>
<li>Place of Birth</li>
</ul>
</div>
<div>
Even a few minutes can shift the rising sign, which changes the entire chart layout. That’s why two people born on the same day can have completely different charts—and different stories.
</div>
<div>
<h2> Our Scientific Approach to Vedic Astrology</h2>
</div>
<div>
<h3> Authentic Vedic Methodology</h3>
Our Janam Patrika analysis follows the time-tested principles of <strong>Brihat Parashara Hora Shastra</strong> and <strong>Jaimini Sutras</strong>, combined with modern computational precision. We use:
<ul>
<li>Classical Planetary Calculations: Based on authentic ephemeris data verified through Swiss Ephemeris</li>
<li>Multiple Divisional Charts: Analysis of all 16 Varga charts for comprehensive insights</li>
<li>Traditional Dasha Systems: Vimshottari, Ashtottari, and Yogini Dasha analysis</li>
<li>Regional Variations: Both North Indian and South Indian chart systems</li>
</ul>
</div>
<div>
H3 Quality Assurance
<ul>
<li>All calculations verified through multiple software systems</li>
<li>Cross-referenced with classical texts and traditional methods</li>
<li>Regular accuracy audits through client feedback spanning 5+ years</li>
<li>Continuous learning from respected Guru lineages in Parampara tradition</li>
</li>
</div>
<div>
<h2> Your Personalised Kundli At AstroOrbits</h2>
</div>
<div>
These days, you don’t have to sit across from a priest or astrologer to get your chart made. There are digital tools that do the math for you, plotting the planets, identifying doshas, and even offering preliminary interpretations.
</div>
<div>
But here’s the thing: while the chart may be generated by software, what you do with it still needs the human touch. At AstroOrbits, we combine both: the speed of tech and the insight of seasoned astrologers. AstroOrbits personalised <strong>Reports prepared by expert Vedic astrologers with years of experience</strong> are known for their accuracy and reliability. Here <strong>real astrologers review interpretations</strong>. 
</div>
<div>
AstroOrbits give you <strong>authentic Janam Kundli based on Brihat Parashara Hora Shastra and Jaimini Sutras</strong> which simply don't have incomprehensible charts and Janam Patrika houses. We understand that if you were a Janam Patrika expert, you would not require others to create and interpret your kundli. That’s why, AstrOrbits gives you a detailed analysis of your Horoscope Chart, position of planets, charts, yogas, dashas etc so that this personalised Horoscope Chart analysis adds significant value to your life. At AstroOrbits, there are <strong>no false promises—genuine, transparent guidance only</strong>.
</div>
<div>
<h2> How Do I Know My AstroOrbits Kundli is Personalised?</h2>
</div>
<div>
Great Question. AstroOrbits believes in the philosophy of ‘When live problems are real, so should be the solutions’. Hence, the Horoscope Chart you get at AstroOrbits is highly personalised to the extent of your time of birth, sometimes even seconds are counted. 
</div>
<div>
<strong>Expert Insight:</strong> "True Vedic astrology considers even the subtle differences in planetary degrees. A planet at 29°58' versus 0°02' can be in entirely different signs, affecting the entire life reading. This precision is what separates authentic analysis from generic predictions."
</div>
<div>
<h2> Following are the aspects of your AstroOrbits kundli which make it completly personalised for you: <h2>
</div>
<div>
<ol>
<li><strong>Your personalised Avakhada Details:</strong> Tells you what the universe has kept for you in your kundli. These personalised details include:
<ul style="list-style-type:disc;">
<li>Nakshatra Lord - Your lunar constellation ruler</li>
<li>Yog - Planetary combination effects</li>
<li>Tithi - Lunar day significance</li>
<li>Tatva - Elemental nature (Earth, Water, Fire, Air, Space)</li>
<li>Paya - Subtle energy classification</li>
<li>Varna - Spiritual temperament category</li>
<li>Sign Lord - Ruling deity influence</li>
<li>Yoni - Animal symbol representing nature</li>
<li>Charan - Nakshatra quarter precision</li>
<li>Karan - Half-tithi influences</li>
<li>Yunja - Time-based classification</li>
<li>Name Alphabet - Phonetic vibration alignment</li>
<li>Gan - Temperamental category (Dev, Manushya, Rakshasa)</li>
<li>Nadi - Pranic energy flow type</li>
<li>Vashya - Mutual attraction principles</li>
<li>Nakshatra - Your birth star constellation</li>
</ul>
</li>
<li><strong>Your Personalised Numerology & Luck Aspects:</strong> This section tells you what the position of plates and their retrogration has in for your luck. This Natal Chart (Vedic) numerology and luck section helps you decide as to what numbers and particular goods are going to be your driving factors in success, health and relations. You get the following personalised insights with AstroOrbits kundli: 
<ul style="list-style-type:disc;">
<li>Destiny Number</li>
<li>Evil Number</li>
<li>Lucky Day</li>
<li>Lucky Mantra</li>
<li>Lucky Stone</li>
<li>Friendly Number</li>
<li>Radical Number</li>
<li>Lucky Color</li>
<li>Lucky God</li>
<li>Lucky Metal</li>
<li>Lucky Substone</li>
<li>Neutral Number</li>
<li>Radical Ruler</li>
</ul>
</li>
<li><strong>Your personalised Planetary Movement section:</strong> This section tells you as to which planets have an important role in your life and which ones are gonna keep influencing your life for years to come. You get an analysis for all the nine planets, about their position in your birth chart, their speed of movement, nature of movement (whether a planet is in retrograde mode or not), among other aspects. Result? You have the following personalised aspects for each planet:
<ul  style="list-style-type:disc;">
<li>Current Sign Position - Which zodiac sign the planet occupies</li>
<li>Sign Lord - Ruler of that zodiac sign</li>
<li>Degree Precision - Exact planetary position (degrees and minutes)</li>
<li>Nakshatra Placement - Which of the 27 lunar mansions</li>
<li>Nakshatra Lord - Ruler of that constellation</li>
<li>House Position - Which life area (1st-12th house) is influenced</li>
<li>Retrogradation Status - Whether planet is moving backward (and its implications)</li>
<li>Planetary Speed - Fast, normal, or slow movement effects</li>
</ul>
<strong>Classical Reference:</strong> According to Jaimini Sutras, the speed and direction of planetary movement significantly affects the timing and intensity of results in one's life.<br><br>
<strong>Example of one our user: Career Breakthrough During Saturn Transit</strong>
Rajesh from Delhi consulted us during his challenging Saturn Mahadasha period in 2019. Our Natal Chart (Vedic) analysis revealed strong 10th house potential with Jupiter's protective aspect, but temporary obstacles due to Shani's 7.5-year cycle. We recommended specific Shani Shanti remedies and career timing guidance. Within 6 months of following our suggestions, he received his dream promotion to Senior Manager, validating our prediction timeline exactly.<br><br>
</li>
<li><strong>Your Personalised Kundli Charts:</strong> Confused about whether to go for south indian kundli charts or north indian kundli chart and their interpretations? Don’t worry. We give you over 20 personalised charts as per your DOB, POB and TOB for both the North Indian and South Indian kundli calculations. Happy already? Here’s more. You get the following kundli charts and their personalised interpretations absolutely free and fully accurate:<br>
<strong>Main Charts:</strong>
<ul style="list-style-type:disc;">
<li>Lagna/Ascendant Chart - Basic birth chart foundation</li>
<li>Moon Chart (Chandra Kundli) - Emotional and mental patterns</li>
<li>Sun Chart (Surya Kundli) - Soul purpose and vitality</li>
</ul>
<strong>Specialized Divisional Charts (Vargas):</strong>
<ul style="list-style-type:disc;"></li>
<li>Namansha (D-1) - Overall life overview</li>
<li>Chalit Chart - Dynamic house positions</li>
<li>Bhavchalit Chart - House-based predictions</li>
<li>Hora (D-2) - Wealth and income analysis</li>
<li>Drekkana (D-3) - Siblings and short journeys</li>
<li>Chaturthamsa (D-4) - Assets and property</li>
<li>Saptamsa (D-7) - Children and creativity</li>
<li>Navamsa (D-9) - Marriage and spiritual growth</li>
<li>Dasamsa (D-10) - Career and profession</li>
<li>Dwadasamsa (D-12) - Parents and ancestry</li>
<li>Shodasamsa (D-16) - Vehicles and comforts</li>
<li>Vimsamsa (D-20) - Spiritual progress</li>
<li>Chaturvimsamsa (D-24) - Learning and education</li>
<li>Saptavimsamsa (D-27) - Strengths and weaknesses</li>
<li>Trimsamsa (D-30) - Misfortunes and challenges</li>
<li>Khavedamsa (D-40) - Auspicious events timing</li>
<li>Akshavedamsa (D-45) - General life issues</li>
<li>Shastiamsa (D-60) - Comprehensive life summary</li>
</ul>
</li>
</ol>


    `,
    column2: `
<ol start="5">
<li><strong>Your Personalised Vimshottari Dasha Analysis:</strong> Yes! You read that right. We provide you accurate and personalised analysis for your Vimshottari Dasha, which especially curated for you on the basis of your date of birth, time of birth, place of birth and your full name. Your personalised Vimshottari Dasha Analysis include: 
<table border="1" cellspacing="0" cellpadding="4">
  <thead>
    <tr>
      <th>Personalised Dasha</th>
      <th>Dasha Periods</th>
      <th>Duration</th>
      <th>Example</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Mahadasha</td>
      <td>Major Period</td>
      <td>Years/Decades</td>
      <td>Venus Mahadasha (20 yrs)</td>
    </tr>
    <tr>
      <td>Antardasha</td>
      <td>Sub-period / Bhukti</td>
      <td>Months/Years</td>
      <td>Sun Antardasha (1 yr)</td>
    </tr>
    <tr>
      <td>Pratyantardasha</td>
      <td>Sub-Sub-Period / Pratyantar Bhukti</td>
      <td>Weeks/Months</td>
      <td>Mars Pratyantardasha (2 months)</td>
    </tr>
    <tr>
      <td>Sookshma Dasha</td>
      <td>Microscopic Period</td>
      <td>Days/Weeks</td>
      <td>Mercury Sookshma Dasha (10 days)</td>
    </tr>
    <tr>
      <td>Pran Dasha</td>
      <td>Breath-Level Period</td>
      <td>Hours/Minutes</td>
      <td>Jupiter Pran Dasha (2 hrs)</td>
    </tr>
  </tbody>
</table>
<div>
<h4> Example from our customer: Successful Marriage After Mangal Dosha Remedy</h4>
Priya from Mumbai had been facing marriage delays for 3 years due to severe Mangal Dosha in her 7th house. Our detailed divisional chart analysis suggested specific Hanuman puja, Red Coral gemstone, and favorable muhurat selection. Following our comprehensive remedy plan, she found her compatible life partner within 8 months and celebrated a harmonious marriage in the auspicious period we recommended
</div>
</li>
<li><strong>Yogini Dasha:</strong> AstroOrbits Free Natal Chart (Vedic) Analysis also include your personalised Yogini Dasha analysis which include the following: 
<ul style="list-style-type: disc;">
<li>Major Yogini dashas: 
<ul style="list-style-type: circle;">
<li>1. Mangala (Moon) – 1 year</li>
<li>2. Pingala (Sun) – 2 years</li>
<li>3. Dhanya (Jupiter) – 3 years</li>
<li>4. Bhramari (Mars) – 4 years</li>
<li>5. Bhadrika (Mercury) – 5 years</li>
<li>6. Ulka (Saturn) – 6 years</li>
<li>7. Siddha (Venus) – 7 years</li>
<li>8. Sankata (Rahu) – 8 years</li>
</ul>
</li>
<li>Minor Yogini dashas:
<ul style="list-style-type: disc;">
<li>Ashtottari Dasha (108 years)</li>
<li>Kalachakra Dasha</li>
<li>Chara Dasha (Jaimini system)</li>
<li>Narayana Dasha</li>
<li>Shoola Dasha, Dwisaptati Sama Dasha</li>
<li>Conditional dasha (Anubandha Dasha)</li>
</ul>
</li>
</ul>
<li><strong>Your Personalised Kundli dosha & remedy analysis:</strong> Astrorbits gives a detailed analysis of your kundli doshas. For example:
<table border="1" cellspacing="0" cellpadding="4">
  <thead>
    <tr>
      <th>Dosha Name</th>
      <th>Formation / Cause</th>
      <th>Effects</th>
      <th>Remedies</th>
      <th>Type</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Kal Sarp Dosha</td>
      <td>All planets between Rahu and Ketu</td>
      <td>Life delays, obstacles, mental stress, career/marital/health issues</td>
      <td>Kal Sarp Shanti Puja, 'Om Namah Shivaya', Gomed/Cat’s Eye, donate black items, fasting on Nag Panchami</td>
      <td>Planetary</td>
    </tr>
    <tr>
      <td>Mangal Dosha (Manglik)</td>
      <td>Mars in 1st, 4th, 7th, 8th, 12th house</td>
      <td>Marital conflicts, delays in marriage, emotional tension</td>
      <td>Mangal Shanti Puja, Hanuman Chalisa, Red Coral, Manglik marriage matching, donate red items</td>
      <td>Marriage</td>
    </tr>
    <tr>
      <td>Pitra Dosha</td>
      <td>Afflicted Sun/Moon or ancestral curse</td>
      <td>Health issues, financial struggles, family problems</td>
      <td>Shraddha/Tarpan rituals, 'Om Namo Pitru Devtaaye Namah', charity to ancestors</td>
      <td>Ancestral</td>
    </tr>
    <tr>
      <td>Shani Dosha</td>
      <td>Malefic Saturn placement</td>
      <td>Career delays, hardships, obstacles</td>
      <td>Shani Shanti Puja, 'Om Sham Shanaishcharaya Namah', Blue Sapphire, donate black items, Saturday fast</td>
      <td>Planetary</td>
    </tr>
    <tr>
      <td>Rahu Dosha</td>
      <td>Malefic Rahu in key houses</td>
      <td>Confusion, sudden changes, mental stress</td>
      <td>Rahu Shanti Puja, 'Om Raam Rahave Namah', Gomed, charity, fasting on Saturdays</td>
      <td>Planetary</td>
    </tr>
    <tr>
      <td>Ketu Dosha</td>
      <td>Malefic Ketu in key houses</td>
      <td>Spiritual detachment, health issues</td>
      <td>Ketu Shanti Puja, 'Om Kem Ketave Namah', Cat’s Eye, Lord Ganesha worship, donate black items</td>
      <td>Planetary</td>
    </tr>
  </tbody>
</table>

<div>
<strong>Expert Insight:</strong> "In our experience, doshas are not curses but karmic indicators guiding us toward specific spiritual growth. The key lies in understanding their deeper purpose and applying remedies with faith and consistency."
</div>
<div>
<h4> Example from our happy customer: Health Recovery Through Dosha Analysis</h4>
Suresh from Pune was experiencing recurring health issues that modern medicine couldn't fully address. Our Vedic Birth Chart analysis revealed Pitra Dosha affecting his 6th house of health, caused by ancestral karmic debts. After performing the recommended Shraddha ceremonies, Gayatri mantra recitation, and charitable acts, his health significantly improved within 3 months, with doctors amazed at his recovery.
</div>
</li>
</ol>
    <div>
<h2>What does your Kundli actually tell you?</h2>
</div>
<div>
Kundli is better at helping you understand your present, and pre-empting your future, enabling you to take pre-emptive actions. For instance, Kundali tells us when our Dashas, Mahadashas, Shani Ki Dhaiyya, Shani Ki Sade Sati etc begin and end. Once a person knows about his/ her Dashas and Doshas, he / she can take remedial actions like conducting dosha / dasha specific poojas, and wearing respective ornaments like bracelets, stone and amulets. 
</div>
<div>
In short, a Vedic Birth Chart/ Jaman Kundli shows you
<ul>
<li>The emotional currents that run beneath your surface</li>
<li>Strengths that you haven’t fully tapped into</li>
<li>Periods where challenges might test your patience</li>
<li>Themes that keep repeating, often for a reason</li>
</ul>
</div>
<div>
It won’t tell you when you’ll fall in love, but it might explain why you resist it. It won’t name your dream job, but it can show you what kind of work brings you energy.
</div>
<div>
<h2> Digital vs. Traditional: Does It Matter?</h2>
</div>
<div>
Some people swear by handwritten charts prepared by family astrologers. Others are happy with instant PDFs from a website.
</div>
<div>
The gospel truth is the innate value of Vedic Birth Chart is derived from its interpretation, not a mere format. An online Vedic Birth Chart can be just as accurate as a hand-drawn one, and in some cases even more accurate than the hand-drawn ones, so long as the inputs are correct and the insights are applied thoughtfully.
</div>
<div>
At AstroOrbits, you can start with a free online chart, and if you want to go deeper, you can book a free session with a real astrologer who’ll walk you through it.
</div>
<div>
<h3> Are There Remedies?</h3>
Yes! And they aren’t superstitions when used correctly. Remedies in astrology aren’t quick fixes. They’re adjustments. Ways of tuning your life to match the rhythm of the energies around you.
Some might involve wearing a stone, chanting a mantra, or even donating to charity. Think of them less as cures and more as course-corrections.
</div>
<div>
<strong>Expert Insight:</strong> "Remedies work through the principle of resonance—like tuning forks, they help align our personal frequency with favorable cosmic vibrations. Success depends on faith, consistency, and proper guidance."
</div>
<div>
<h2> Final Thoughts</h2>
</div>
<div>
Your Janam Kundli isn’t a promise. It’s a possibility. A chance to understand your nature in a way that’s layered, nuanced, and rooted in thousands of years of observation.
</div>
<div>
So whether you’re a believer, a skeptic, or just someone looking for answers, maybe give your birth chart a glance. You might be surprised by how familiar it feels.
</div>
<div>
After all, the sky at the moment you were born was never random. Maybe it’s been waiting all this time for you to notice.
</div>
<div>
<h3> Our Commitment to Ethical Practice</h3>
We uphold the highest standards of authentic Vedic astrology:
No false promises about guaranteed future outcomes
Honest assessment of planetary influences and probabilities
Clear communication of both favorable and challenging periods
Respectful guidance empowering informed personal decisions
Continuous learning from classical texts and experienced mentors
</div>
<div>
    Important Disclaimer<br>
<em>
"Astrological guidance is intended for educational, spiritual, and self-reflection purposes based on ancient Vedic wisdom. While we maintain the highest standards of calculation accuracy and interpretive expertise, astrology provides insights and possibilities rather than absolute certainties. This guidance should complement, never replace, professional medical, legal, or financial advice. Your free will, personal efforts, and life choices ultimately shape your destiny. Individual results may vary based on karma, effort, and circumstances beyond astrological influence."</em>
</div>
<div>
<em>
Last Updated: August 23, 2025
Content Reviewed: Monthly by certified experts
Accuracy Verified: Cross-referenced with multiple traditional sources</em>
</div>
`
};

export const kundliFaqCard: IFAQCard[] = [
    {
        ques: `What information do I need to create my Kundli?`,
        ans: `You just need the following basic details:
        <ul>
<li>Your full name - This connects to the phonetic vibrations and numerological aspects</li>
<li>Date of birth - Obviously crucial for planetary positions</li>
<li>Time of birth - This is where most people get tripped up. Even a difference of 4-6 minutes can shift your Lagna (rising sign), which changes your entire chart interpretation. </li>
<li>Place of birth: The latitude and longitude affect how planets appear in your local sky</li>
</ul>
Although if you don’t know your accurate time of birth, alternate methods of kundli creation like Prashna kundli can help you do it.`,
    },
    {
        ques: `How accurate are online Kundli calculators?`,
        ans: `Here's something that surprises many people: a good online Kundli calculator is often more accurate than hand-drawn charts from decades ago. Why? Because computers don't make calculation errors, and they use precise astronomical databases.<br><br>
At AstroOrbits, our calculations are accurate to the second. The real difference isn't in the calculations anymore, it's in the interpretation. The days of worrying about computational accuracy are behind us. `,
    },
    {
        ques: `What's the difference between Kundli and daily horoscope?`,
        ans: `This is like asking the difference between a detailed medical report about your specific health and a general health tip that applies to millions of people.
<br><br>
Daily horoscopes are written for everyone born under the same sun sign - that's roughly 1/12th of the world's population! They're based on one piece of your chart (your sun sign) and use generic predictions.
<br><br>
Whereas, a Kundli deals with all the nine planets, their positions, and their effects on all the twelve houses in your kundli, and the ripple effects these 12 houses have on your life.`,
    },
    {
        ques: `Can I make a Kundli without exact birth time?`,
        ans: `Yes you can, but it might affect the accuracy of your kundli analysis as without the exact time, we can't determine:
        <ul>
<li>Your rising sign accurately</li>
<li>Which houses the planets occupy</li>
<li>The strength and timing of various planetary periods</li>
<li>Precise predictions about life events</li>
</ul>
<br><br>
But if you don’t know your exact time of birth, there are other alternate ways of making your kundli like Prashna Kundli, which does not require exact time of birth.`,
    },
    {
        ques: `What are the 12 houses in a Kundli?`,
        ans: `The 12 houses and their importance in a kundli are as follows:<br>
1st House - Your personality, physical appearance, overall approach to life<br>
2nd House - Money, possessions, family wealth, speech, food habits<br>
3rd House - Siblings, communication skills, short travels, courage<br>
4th House - Home, mother, emotional foundation, property, inner peace<br>
5th House - Children, creativity, romance, education, past life karma<br>
6th House - Health, daily routine, enemies, service, work environment<br>
7th House - Marriage, business partnerships, open enemies, foreign lands<br>
8th House - Longevity, hidden knowledge, joint finances, transformation<br>
9th House - Higher learning, spirituality, father, long-distance travel, luck<br>
10th House - Career, reputation, status, government connections<br>
11th House - Friends, gains, income from career, fulfillment of desires<br>
12th House - Spirituality, foreign connections, expenses, losses, moksha`,
    },
    {
        ques: `What are Nakshatras in Kundli analysis?`,
        ans: `Nakshatras are the 27 lunar mansions that provide much deeper insights into your personality and life path. These Nakshatras provide insights into:
        <ul>
<li>Your core mental nature and thinking patterns</li>
<li>Your emotional responses and instinctive reactions</li>
<li>Compatible partners for marriage</li>
<li>Favorable career directions</li>
<li>Your spiritual inclinations</li>
</ul>`,
    },
    {
        ques: `How is North Indian Kundli different from South Indian?`,
        ans: `This is purely about presentation format - the underlying calculations and meanings are identical. 
<br><br>
North Indian style shows houses as fixed squares with zodiac signs rotating within them, whereas South Indian style shows zodiac signs in fixed positions with houses rotating. Leo is always at the top, Aquarius at the bottom.
<br><br>
Some people find North Indian charts easier to read because the house positions never change. Others prefer South Indian charts because the zodiac signs stay in their traditional positions.
<br><br>
We provide both formats at AstroOrbits because we've found that people often have personal preferences based on what they learned first or what their family astrologer used.`,
    },
    {
        ques: `What are divisional charts (Vargas) in Kundli?`,
        ans: `Divisional charts are basically specialized charts which deal with a particular aspect of your overall life. Some of the most important divisional charts under the Vedic astrology used by AstroOrbits include: 
        <ul>
<li>Navamsa (D-9) - Your marriage, spouse, and spiritual growth</li>
<li>Dasamsa (D-10) - Career and professional success</li>
<li>Saptamsa (D-7) - Children and creativity</li>
<li>Dwadasamsa (D-12) - Your parents and ancestral influences</li>
</ul><br><br>

We analyze up to 16 different divisional charts to give you the most complete picture possible of each life area.`,
    },
    {
        ques: `Can Kundli predict the exact future?`,
        ans: `This is one of the most important questions, and the honest answer is: not exactly, and that's actually a good thing. Kundli provides detailed insights into what might happen in future in different aspects of your, but not exact future as the kundli predictions tell you as changes in your plantes are going to affect you, depending on what specific question you are trying to find an answer for.
        <br><br>
        What Kundli can do:
        <ul>
        <li>Predict the general themes and challenges of different life periods</li>
<li>Show you when opportunities are likely to appear</li>
<li>Reveal your natural strengths and potential obstacles</li>
<li>Guide you on favorable timing for important decisions</li>
</ul>
<br><br>
What it cannot do:
<ul>
<li>Tell you exactly what will happen on a specific date</li>
<li>Override your free will and personal choices</li>
<li>Guarantee any particular outcome</li>
</ul>
<br><br>
The most accurate part of Kundli predictions is timing - when certain influences will be strongest in your life. How you respond to those influences ultimately shapes your actual experience.
`,
    },
    {
        ques: `Is Kundli scientifically accurate?`,
        ans: `The astronomical calculations in Kundli are completely scientific and mathematically precise. We use the same ephemeris data that astronomers use to track planetary positions.
<br><br>
Where the "science" gets more complex is in the interpretative framework. Vedic astrology is based on thousands of years of observed correlations between celestial events and human experiences. 
<br><br>
Modern research has found interesting correlations - for example, studies showing that people are more likely to be born during certain moon phases, or that solar activity affects human behavior.`,
    },
];